### ISSUE TITLE
Figure out a color scheme

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/tasks#33]
## Colors

```scss
$color-purple: hsl(237, 100%, 75%);
$color-purple-dark: hsl(237, 100%, 70%);
$color-purple-darker: hsl(237, 100%, 65%);
$color-purple-darkest: hsl(237, 100%, 60%);
$color-purple-light: hsl(237, 100%, 80%);
$color-purple-lighter: hsl(237, 100%, 85%);
$color-purple-lightest: hsl(237, 100%, 90%);
$color-white: hsl(0, 0%, 97%);
$color-white-darker: hsl(0, 0%, 92%);
$color-white-darkest: hsl(0, 0%, 87%);
```

## Fonts

```html
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
```

## Classes

```scss
.color-purple {color: $color-purple;}

.color-bg-purple {
    background-color: $color-purple;
    color: white;
}

.custom-font {font-family: 'Jost', sans-serif;}

.custom-font-bold {
    font-family: 'Jost', sans-serif;
    font-weight: bold;
}
```
